### ISSUE TITLE
Improve usage guide

### ISSUE THREAD

**Issue by williamoverton** [orchidsoftware/experiment#3]
It would be great if you could provide usage examples for:

- Adding and removing tests
- Changing view contents based on which tests a user is part of

Thanks,

Will

**Comment by tabuna** [comment]
Hello @williamoverton 

The main use is to add some cookie value, for single-page applications.
Since they do not have the ability to accurately determine the rotation of their experiments and in this case rely on the back-end.


```php
// example for middleware

$experiment = new Experiment('AB_YOUR_KEY');

$experiment->startAndSaveCookie([
        'red_button' => 60,
        'blue_button' => 30,
        'black_button' => 10,
]);
        
return $next($request);
```


After the request, you can get this value, for example in JS:

```javascript
// Get value from cookie string
let cookieButtonValue = document.cookie.replace(/(?:(?:^|.*;\s*)AB_YOUR_KEY\s*\=\s*([^;]*).*$)|^.*$/, "$1");


// Very conditional example
if(cookieButtonValue == 'red_button') {
  document.getElementById('myButton').className = 'btn-red';
}

if(cookieButtonValue == 'blue_button') {
  document.getElementById('myButton').className = 'btn-blue';
}

//...etc

```


In order to remove the experiment you just need to remove you do not need the value from the array. And new users will not be assigned this cookie.
